### ISSUE TITLE
Cluster creation fails on the newly added PVE nodes due to connection issues.

### ISSUE THREAD

**Issue by edikmkoyan** [infraheads/turnk8s#1]
I changed the value of the PROXMOX_IP to the IP of the newly added PVE host. The workflow starts and hangs as the GitHub runner does not contain the new PVE host's SSH fingerprint. However, when "yes" is entered as an answer, it fails anyway. Please take a look at the details in the screenshot attached. 
<img width="647" alt="Screenshot 2024-04-29 at 19 52 13" src="https://github.com/infraheads/turnk8s/assets/10867292/13a13169-8e76-46d3-b851-cdeebdc8b2a7">

**Comment by edikmkoyan** [comment]
@hakobian4 I am re-running the workflow; it seems to be working when the SSH fingerprints are present. Thus, I guess that is the only issue that should be solved with the GitHub self-runner provisioning automation. I will move it to a milestone.

**Comment by hakobian4** [comment]
Currently our workflows are run in a container and we don'y have that issue anymore. So I'll close this issue. Thanks
