### ISSUE TITLE
Permanent IP to Netris VMs

### ISSUE THREAD

**Issue by hakobian4** [infraheads/turnk8s#2]
The IP addresses of Netris VMs are changed when the VMs are rebooted. Please add the MAC addresses of VMs on the router (bc:24:11:d3:af:32 - 192.168.1.9, bc:24:11:fb:95:b9 - 192.168.1.15, bc:24:11:24:1d:60 - 192.168.1.16). Thanks. @edikmkoyan

**Comment by edikmkoyan** [comment]
I configured the DHCP server; however, this does not solve the main problem, which must be described separately.
